setwd("C:/Users/Samsung/Downloads/eda")
data<-read.table("household_power_consumption.txt", header=T,sep=";" ,na="?")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
mydata<-subset(data,Date=="2007-02-01" | Date=="2007-02-02")
datetimecomb<-paste(as.Date(mydata$Date),mydata$Time)
mydata$Datetime <- as.POSIXlt(datetimecomb)
png(file="plot2.png")
with(mydata,plot(Datetime,Global_active_power,ylab="Global Active Power(kilowatts)",xlab="", type="l"))
dev.off()